---
# file: tasks/main.yml

- import_tasks: multi_os.yml

- name: main | Install dependencies Debian
  apt: 
    name: "{{ common_packages| join(',') }}"
    state: present
    cache_valid_time: 43200
    #force: yes
  environment:
    DEBIAN_FRONTEND: noninteractive
  when: ansible_os_family == 'Debian'

- name: main | Install dependencies RedHat
  package: 
    name: "{{ common_packages| join(',') }}"
    state: present
  when: ansible_os_family == 'RedHat'

#TODO: copying the plugins with synchronize will not work with podman
# keeping the plugins in files in the role is not the best and smartest option
# Should consider moving the files to another repository.
- name: Install NRPE plugins
  copy:
      src: nrpe_plugins/
      dest: /usr/lib/nagios/plugins/
      mode: 0755

- name: Install plugins from git clone
  git:
    repo: "{{ item.repo }}"
    clone: yes
    dest: "{{ item.dest }}"
    depth: 1
  with_items: "{{ nagios_plugins_repos }}"
  when: common_nagios_nrpe_clone_plugins

# TODO: Currently all the plugins configuration are in the nrpe.cfg file instead of nrpe.d dir with individual files.
# Should consider moving the files to another repository.
- name: configure nagios nrpe.cfg client
  template:
    src: nrpe.cfg.j2
    dest: /etc/nagios/nrpe.cfg
  notify:
    - restart nagios-nrpe-server

- name: Make sure nagios-nrpe-server is started and enabled to autostart
  service:
    name: "{{ common_nrpe_service }}"
    state: started
    enabled: yes

- name: lineinfile - configure sudoers to allow check_linux_stats.pl permissions
  lineinfile:
    path: "{{ common_sudoers_file }}"
    regexp: '{{ item.src }}'
    line: '{{ item.value }}'
    validate: '/usr/sbin/visudo -cf %s'
  with_items:
    - src: '^nagios ALL=[(]root[)] NOPASSWD\:/usr/bin/perl /usr/lib/nagios/plugins/check_linux_stats.pl'
      value: 'nagios ALL=(root) NOPASSWD:/usr/bin/perl /usr/lib/nagios/plugins/check_linux_stats.pl *'
    - src: '^nagios ALL=[(]root[)] NOPASSWD\:/usr/lib/nagios/plugins/check_disk'
      value: 'nagios ALL=(root) NOPASSWD:/usr/lib/nagios/plugins/check_disk'
